### ISSUE TITLE
contribute any data structure problem.

### ISSUE THREAD

**Issue by sourav2002** [sourav2002/DataStructure-And-Algo#40]

**Comment by manipta** [comment]
Do code need to be in java only?

**Comment by Aniumbott** [comment]
would be happy to work on anything. 🙌

**Comment by ananya-1112** [comment]
Would love to put my work on this

**Comment by sourav2002** [comment]
> Do code need to be in java only?

If you want to upload code in any language besides JAVA, make a new folder and upload it there.

**Comment by manipta** [comment]
> > Do code need to be in java only?
> 
> If you want to upload code in any language besides JAVA, make a new folder and upload it there.

okk,got it.

**Comment by SohamRatnaparkhi** [comment]
I would like to add tree problems in Java

**Comment by sourav2002** [comment]
@ananya-1112, @Aniumbott you are welcome to contribute.😊 
If you have any doubt, read CONTRIBUTING.md file

**Comment by Aniumbott** [comment]
thank you @sourav2002

**Comment by ashankritwik07** [comment]
I would love to contribute to the repo, please assign me this

**Comment by manishtambe** [comment]
I would love to contribute few linked list problem can you assign it to me ?

**Comment by Aman149** [comment]
I would love to contribute few array questions.

**Comment by anmolkulshrestha** [comment]
can i add longest_substring_without_repeating_character problem in cpp,java and kotlin language as part of hacktober fest and few other dsa problems in all three languages as mentioned

**Comment by anmolkulshrestha** [comment]
pls assign it to me

**Comment by manishtambe** [comment]
@sourav2002  Added Linked List Problem Please Merge My PR for #40

**Comment by anirudh0806** [comment]
I would like to contribute some good problems. Please assign.

**Comment by VINAYBOYAT11** [comment]
hey sourav i have contributed codes could you please approve it
